name: Build and Run .NET Code



on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # - cron:  '5,10,15,20,25,30,35,40,45,50,55 * * * *'
    - cron:  '0,5,10,15,20,25,30,35,40,45,50,55 * * * *'
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # 选择你需要的 .NET 版本

      - name: Restore dependencies
        run: dotnet restore Sina-News-C-Sharp/Sina-News-C-Sharp.csproj

      - name: Build
        run: dotnet build Sina-News-C-Sharp/Sina-News-C-Sharp.csproj --no-restore

      - name: Run tests
        run: dotnet test Sina-News-C-Sharp/Sina-News-C-Sharp.csproj --no-build --verbosity normal

      - name: Print working directory
        run: pwd
        
      - name: List files in project directory
        run: ls -la  Sina-News-C-Sharp

  push_changes:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Run the application
        run: dotnet run --project Sina-News-C-Sharp/Sina-News-C-Sharp.csproj # 替换为你的项目名称

      - name: Push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m 'Automated commit from GitHub Actions'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GIT_TOKEN }}
